version: "3.7"
services:

  authority-service:
    build:
      context: .
      dockerfile: ./bin/authority-service/docker/authority-service.Dockerfile

  validator-alice-1:
    image: parity/substrate
    ports:
      - "9944:9944"
      - "9615:9615"
    command:
      - "substrate"
      - "--node-key"
      - "0000000000000000000000000000000000000000000000000000000000000001"
      - "--base-path"
      - "/tmp/alice-1"
      - "--chain=local"
      - "--port"
      - "30333"
      - "--validator"
      - "--alice"
      - "--bootnodes"
      - "/dns/validator-bob/tcp/30333/p2p/12D3KooWHdiAxVd8uMQR1hGWXccidmfCwLqcMpGwR6QcTP6QRMuD"
      - "--remote-authority"
      - "http://authority-service:8000"
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      - "-lafg=debug"

  validator-alice-2:
    image: parity/substrate
    command:
      - "substrate"
      - "--base-path"
      - "/tmp/alice-2"
      - "--chain=local"
      - "--port"
      - "30333"
      - "--validator"
      - "--alice"
      - "--bootnodes"
      - "/dns/validator-bob/tcp/30333/p2p/12D3KooWHdiAxVd8uMQR1hGWXccidmfCwLqcMpGwR6QcTP6QRMuD"
      - "--remote-authority"
      - "http://authority-service:8000"
      - "-lafg=debug"

  validator-bob:
    image: parity/substrate
    command:
      - "substrate"
      - "--node-key"
      - "0000000000000000000000000000000000000000000000000000000000000002"
      - "--base-path"
      - "/tmp/bob"
      - "--chain=local"
      - "--port"
      - "30333"
      - "--validator"
      - "--bob"
      - "--bootnodes"
      - "/dns/validator-alice-1/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
      - "--no-telemetry"
      - "-lafg=debug"

  validator-eve:
    image: parity/substrate
    command:
      - "substrate"
      - "--node-key"
      - "0000000000000000000000000000000000000000000000000000000000000003"
      - "--base-path"
      - "/tmp/eve"
      - "--chain=local"
      - "--port"
      - "30333"
      - "--validator"
      - "--eve"
      - "--bootnodes"
      - "/dns/validator-alice-1/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
      - "--no-telemetry"
      - "-lafg=debug"

  validator-dave:
    image: parity/substrate
    command:
      - "substrate"
      - "--node-key"
      - "0000000000000000000000000000000000000000000000000000000000000004"
      - "--base-path"
      - "/tmp/dave"
      - "--chain=local"
      - "--port"
      - "30333"
      - "--validator"
      - "--dave"
      - "--bootnodes"
      - "/dns/validator-alice-1/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
      - "--no-telemetry"
      - "-lafg=debug"

  validator-charlie:
    image: parity/substrate
    command:
      - "substrate"
      - "--node-key"
      - "0000000000000000000000000000000000000000000000000000000000000005"
      - "--base-path"
      - "/tmp/charlie"
      - "--chain=local"
      - "--port"
      - "30333"
      - "--validator"
      - "--charlie"
      - "--bootnodes"
      - "/dns/validator-alice-1/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
      - "--no-telemetry"
      - "-lafg=debug"
